### PR TITLE
Added HTML Tag <br /> as BBCode [br] tag.

### PR DESCRIPTION
**Pull request by Cr4zyFl1x**
I just thought that it would be helpful for some users to have the HTML <br /> Tag implemented in BBCode.
So this is why I added it as an BBCode-Tag

`[br] => <br />`

Best regards,
Florian K.

### CODE REVIEW

**Comment by chriskonnertz** [comment]
@Cr4zyFl1x Hi!

Why did you close this merge request? 🧐

**Comment by mattatobin** [comment]
To be honest, this needs to be configurable cause `<br />` is only valid for `xhtml` doctypes.. This would be invalid for `html4` and I think `html5` but don't quote me on that.

**Comment by Cr4zyFl1x** [comment]
Is that so important?
I think a lot of people don't pay attention to these tags and their doctype.

**Comment by mattatobin** [comment]
They really don't have to because most people just use `html5` these days..

I don't, so it matters. It would also matter if someone was still using `html4`.

**Comment by wolfbeast** [comment]
> 
> Is that so important? 

Yes it is, very much so. Doctypes directly determine how a multi-doctype parser handles a document. Like... every browser under the sun.

**Pull request closed without merging**
